# Generated by Django 4.2.4 on 2023-10-08 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_todo', '0006_alter_todos_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todos',
            name='status',
            field=models.CharField(choices=[('a', 'active'), ('d', 'done'), ('n', 'not yet')], max_length=15, verbose_name='Status'),
        ),
    ]
