# Generated by Django 4.2.4 on 2023-10-08 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('temp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Javob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matn', models.TextField()),
                ('yaratilgan_sana', models.DateTimeField(auto_now_add=True)),
                ('shikoyat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='temp.shikoyat')),
            ],
        ),
    ]
