# Generated by Django 4.2.4 on 2023-10-08 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('temp', '0004_savoljavob_is_superadmin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='savoljavob',
            name='javoblar',
        ),
        migrations.RemoveField(
            model_name='savoljavob',
            name='savol',
        ),
        migrations.RemoveField(
            model_name='shikoyat',
            name='user',
        ),
        migrations.DeleteModel(
            name='Javob',
        ),
        migrations.DeleteModel(
            name='SavolJavob',
        ),
        migrations.DeleteModel(
            name='Shikoyat',
        ),
    ]
