# Generated by Django 4.2.4 on 2023-11-10 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temp', '0007_complaint_reply_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutpage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='about/'),
        ),
        migrations.AlterField(
            model_name='books',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='qrcode',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='qrcodes/'),
        ),
    ]
